### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by xilopaint** [Acidham/search-alfred-workflows#1]
[12:23:37.469] Search Alfred Workflows[Script Filter] Queuing argument '(null)'
[12:23:38.449] Search Alfred Workflows[Script Filter] Script with argument '(null)' finished
[12:23:38.454] ERROR: Search Alfred Workflows[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/<arthur>/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/com.apple.alfred.workflow.alfdir/alf.py", line 132, in <module>
    quicklook_url = create_hint_file(os.path.dirname(wf_path), content)
  File "/Users/arthur/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/com.apple.alfred.workflow.alfdir/alf.py", line 100, in create_hint_file
    f.write(content)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 346-347: ordinal not in range(128)

**Comment by Acidham** [comment]
Did this happen when after you typed "alf" without additional characters? Seems you have a workflow installed with a symbol e.g. →  or something? Would be great if you could tell me...

**Comment by xilopaint** [comment]
Yes, it happened without additional characters. I'm not sure if I have a workflow with some non-standard character (I have a ton of workflows) but it's quite possible due the nature of the error. I've submitted a PR with the fix.
