### ISSUE TITLE
try catch error.

### ISSUE THREAD

**Issue by touchmii** [Acidham/search-alfred-workflows#13]
[12:12:41.607] Search Alfred Workflows[Script Filter] Queuing argument '(null)'
[12:12:42.087] Search Alfred Workflows[Script Filter] Script with argv '(null)' finished
[12:12:42.092] ERROR: Search Alfred Workflows[Script Filter] Code 1: PYTHON VERSION: 3.9.6 (default, May  7 2023, 23:32:44) 
[Clang 14.0.3 (clang-1403.0.22.14.1)]
Traceback (most recent call last):
  File "/Users/home/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.20ADA99F-BE34-4B9F-A7F9-264462EDBBAE/Workflows.py", line 78, in _get_plist_info
    return load(fp)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/plistlib.py", line 875, in load
    return p.parse(fp)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/plistlib.py", line 177, in parse
    self.parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 215, column 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/home/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.20ADA99F-BE34-4B9F-A7F9-264462EDBBAE/Workflows.py", line 110, in get_item
    plist_info = self._get_plist_info(plist_path)
  File "/Users/home/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.20ADA99F-BE34-4B9F-A7F9-264462EDBBAE/Workflows.py", line 80, in _get_plist_info
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/home/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.20ADA99F-BE34-4B9F-A7F9-264462EDBBAE/alf.py", line 146, in <module>
    Workflows = Workflows()
  File "/Users/home/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.20ADA99F-BE34-4B9F-A7F9-264462EDBBAE/Workflows.py", line 54, in __init__
    self.workflows = self._get_workflows_list()
  File "/Users/home/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.20ADA99F-BE34-4B9F-A7F9-264462EDBBAE/Workflows.py", line 179, in _get_workflows_list
    i = self.get_item(w)
  File "/Users/home/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.20ADA99F-BE34-4B9F-A7F9-264462EDBBAE/Workflows.py", line 167, in get_item
    sys.stderr.write(f"Error: {e} ({name};{plist_path})\n")
UnboundLocalError: local variable 'name' referenced before assignment

```

# Workflows.py 

# line 100
def get_item(self, plist_path):
        """Get content of worfklow item

        Args:
            plist_path (str): Path to info.plist

        Returns:
            dict: Content of info.plist
        """
        try:
            plist_info = self._get_plist_info(plist_path)
            name = plist_info.get('name')
            desc = plist_info.get('description')

# line 165 should change
        except Exception as e:
            if 'name' in locals():
                sys.stderr.write(f"Error: {e} ({name};{plist_path})\n")
           # unnecessary
           #else:
           #     sys.stderr.write()
            return None
```

When self.__get_plist_info() raise error name is not define, and cant catch its error, So there is no need to print the error that occurred in __get_plist_info().

**Comment by touchmii** [comment]
It seems that this workflow caused the error, its cannot be searched.

https://github.com/xeric/alfred-find2kill

**Comment by Acidham** [comment]
I tried to reproduce, but Alfred does not allow me to save WF without a Name.

**Comment by touchmii** [comment]
you can test this workflow, https://github.com/xeric/alfred-find2kill.

**Comment by touchmii** [comment]
> you can test this workflow, https://github.com/xeric/alfred-find2kill.
> […](#)

It is plistlib parsing info.plist file error, Find2Kill's info.plist file contains a script has a few special characters, after deleting it will be normal.
