### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by nikitavoloboev** [Acidham/search-alfred-workflows#6]
Alfred ver. 4.0.2
macOS ver. 10.14.5

Log:
```bash
[22:57:09.119] ERROR: Search Alfred Workflows[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C31AF14C-A953-4CDF-9044-645939CF533F/alf.py", line 102, in <module>
    Workflows = Workflows()
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C31AF14C-A953-4CDF-9044-645939CF533F/Workflows.py", line 23, in __init__
    self.workflows = self._get_workflows_list()
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C31AF14C-A953-4CDF-9044-645939CF533F/Workflows.py", line 109, in _get_workflows_list
    i = self.get_item(w)
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C31AF14C-A953-4CDF-9044-645939CF533F/Workflows.py", line 76, in get_item
    desc = plist_info['description']
KeyError: 'description'
```

**Comment by Acidham** [comment]
Please upgrade to 0.7.0 and re-try.

**Comment by nikitavoloboev** [comment]
Great. It works.
